# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
name: Aliyun Signin

on:

  schedule:

   # 每天国际时间 14:40 运行一次, 中国时间 22:40

    - cron: '40 14 * * *'

  workflow_dispatch:

jobs:

  signin:

    name: Aliyun Signin

    runs-on: ubuntu-latest

    steps:

      - uses: ImYrS/aliyun-auto-signin@main

        with:

          REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}

          GP_TOKEN: ${{ secrets.GP_TOKEN}}

          PUSH_TYPES: ''

          DO_NOT_REWARD: 'true'

          SERVERCHAN_SEND_KEY: ${{ secrets.SERVERCHAN_SEND_KEY }}

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}

          PUSHPLUS_TOPIC: ${{ secrets.PUSHPLUS_TOPIC }}

          SMTP_HOST: ${{ secrets.SMTP_HOST }}

          SMTP_PORT: ${{ secrets.SMTP_PORT }}

          SMTP_TLS: ${{ secrets.SMTP_TLS }}

          SMTP_USER: ${{ secrets.SMTP_USER }}

          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

          SMTP_SENDER: ${{ secrets.SMTP_SENDER }}

          SMTP_RECEIVER: ${{ secrets.SMTP_RECEIVER }}

          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}

          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

          CQHTTP_ENDPOINT: ${{ secrets.CQHTTP_ENDPOINT }}

          CQHTTP_USER_ID: ${{ secrets.CQHTTP_USER_ID }}

          CQHTTP_ACCESS_TOKEN: ${{ secrets.CQHTTP_ACCESS_TOKEN }}
